insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Hills-Watsica', '864090096', 'Continental', 964, null, '75342', 'Sumberbatas');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Douglas Group', '594535551', 'Buena Vista', 670, 17, '37177', 'Paobulan');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Blick, Huels and Cronin', '658752677', 'Service', 314, null, '99231', 'Zuya');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Walker-Rice', '784836726', 'Pond', 576, null, '26580', 'Stutterheim');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Morar, Christiansen and Herman', '879776362', 'Red Cloud', 106, 23, '25418', 'Tuchomie');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Dickens LLC', '299803206', 'Haas', 296, null, '61187', 'Kallithéa');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Huels, Hilll and Emard', '328513814', 'Columbus', 42, null, '63550', 'Lefkímmi');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Langworth-Doyle', '043032182', 'Badeau', 59, 3, '57350', 'Tambakrejo');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Powlowski-Beier', '995650795', 'Holmberg', 233, null, '57527', 'San Felipe');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Boehm-Runolfsson', '648830647', 'Talisman', 480, 4, '64904', 'Tarbes');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Shields-Bins', '719143984', 'Graceland', 721, null, '84986', 'San Miguel del Padrón');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Carter LLC', '741678167', 'Shoshone', 520, null, '11223', 'Sendung');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Fay LLC', '106280357', 'Little Fleur', 243, 29, '67801', 'Virginia Beach');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Cruickshank-Zemlak', '101137291', 'Fairfield', 765, null, '43927', 'Paagahan');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Schinner Group', '743833821', 'John Wall', 459, null, '07408', 'Velké Karlovice');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Kuhic-Cremin', '082549370', 'Luster', 737, null, '29311', 'Hartford');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Jerde-Jakubowski', '996656678', 'Menomonie', 164, null, '17428', 'Siverskiy');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Trantow, Koss and Sanford', '566115567', 'Thackeray', 324, null, '12921', 'Puerto Santander');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Langworth-Moore', '702213273', 'Union', 732, null, '40237', 'Momanalu');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('VonRueden-Corkery', '632942285', 'Golf', 367, null, '14174', 'Oehala');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Ankunding Group', '133182175', 'Claremont', 65, 11, '12322', 'Taipa');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Wisoky-Reynolds', '650186659', '5th', 299, null, '88843', 'Solnice');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Schinner-Hilpert', '852781463', 'Magdeline', 586, 12, '19946', 'Malangwa');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Klein, Luettgen and McClure', '497642132', 'Redwing', 576, 16, '73188', 'Jingping');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Wuckert Inc', '986477206', 'Vahlen', 649, null, '81248', 'Madrid');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Kuhic-Crist', '741042775', 'Columbus', 622, null, '90756', 'Iaçu');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Hessel, Kshlerin and Gislason', '947779184', 'Coleman', 771, 28, '34800', 'Warsaw');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Little Inc', '139069536', 'Bonner', 798, null, '28816', 'Sysert’');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Stiedemann, Moore and Will', '705777165', 'Parkside', 508, 3, '94995', 'Corujeira');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Cormier-Langosh', '828975386', 'Debs', 839, null, '65792', 'Arraial do Cabo');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Medhurst and Sons', '220098651', 'Memorial', 446, 27, '78772', 'Sharjah');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Fay and Sons', '317888246', 'Scofield', 150, null, '33093', 'Andrezieux-Boutheon');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Crist, Wilderman and Franecki', '391091541', 'Waywood', 40, 13, '39122', 'Guangpu');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Roberts-Kuhn', '468399623', 'Manufacturers', 371, null, '25668', 'Chengtian');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Kuhlman-Smitham', '273291638', 'Sunnyside', 390, 27, '66803', 'Neochóri');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Abernathy LLC', '015434371', 'Express', 565, 10, '62250', 'Yezhi');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Kohler, Botsford and Rempel', '937872438', 'Tennyson', 197, null, '92420', 'Nhon Trach');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Towne Group', '435612758', 'Sugar', 775, null, '34003', 'Namie');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('O''Conner LLC', '812006782', 'Dennis', 669, null, '37805', 'Berlin');
insert into Dostawcy (DostawcaNazwa, Telefon, Ulica, NumerDomu, NumerMieszkania, KodPocztowy, Miasto) values ('Robel-Rempel', '740870815', 'Beilfuss', 989, null, '59236', 'Zhukovo');
